### ISSUE TITLE
NullReferenceException executing code fixes (seems new in VS 16.8.x)

### ISSUE THREAD

**Issue by BrightLight** [BrightLight/YouShouldSpellcheck.Analyzer#16]
I get a NullReferenceException when an issue is shown and I want to open the available code fixes ("suggestions") in the context menu. I have not changed the analyzer for at least months. Only thing that has changed is that I have updated my Visual Studio 2019.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at YouShouldSpellcheck.Analyzer.YouShouldSpellcheckAnalyzerCodeFixProvider.Suggestions(String word,IEnumerable`1 languages,Dictionary`2 allSuggestions)
   at YouShouldSpellcheck.Analyzer.YouShouldSpellcheckAnalyzerCodeFixProvider.Suggestions(Diagnostic diagnostic,String& offendingWord,Dictionary`2 allSuggestions,IEnumerable`1 languages)
   at async YouShouldSpellcheck.Analyzer.TextCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

![TextCodeFixProvider](https://user-images.githubusercontent.com/1859278/107437499-64942f00-6b2f-11eb-911b-ac85a7e261c8.png)

**Comment by BrightLight** [comment]
Still observable in Visual Studio 2022. Interestingly, no problem in Rider.
